// flow-typed signature: cdd3b0afe5c672500cc6dfa5359b1dc3
// flow-typed version: <<STUB>>/karma-chai-sinon_v^0.1.5/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-chai-sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-chai-sinon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-chai-sinon/adapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-chai-sinon/adapter.js' {
  declare module.exports: $Exports<'karma-chai-sinon/adapter'>;
}
declare module 'karma-chai-sinon/index' {
  declare module.exports: $Exports<'karma-chai-sinon'>;
}
declare module 'karma-chai-sinon/index.js' {
  declare module.exports: $Exports<'karma-chai-sinon'>;
}
