// flow-typed signature: 769b6f815e8c8c0399746f6845efa1af
// flow-typed version: <<STUB>>/preact-css-transition-group_v^1.1.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-css-transition-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-css-transition-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-css-transition-group/dist/preact-css-transition-group' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/dist/preact-css-transition-group.min' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/rollup.config' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/src/CSSCore' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/src/CSSTransitionGroup' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/src/CSSTransitionGroupChild' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/src/index' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/src/TransitionChildMapping' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/src/TransitionEvents' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/src/util' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/tests/index' {
  declare module.exports: any;
}

declare module 'preact-css-transition-group/tests/karma.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-css-transition-group/dist/preact-css-transition-group.js' {
  declare module.exports: $Exports<'preact-css-transition-group/dist/preact-css-transition-group'>;
}
declare module 'preact-css-transition-group/dist/preact-css-transition-group.min.js' {
  declare module.exports: $Exports<'preact-css-transition-group/dist/preact-css-transition-group.min'>;
}
declare module 'preact-css-transition-group/rollup.config.js' {
  declare module.exports: $Exports<'preact-css-transition-group/rollup.config'>;
}
declare module 'preact-css-transition-group/src/CSSCore.js' {
  declare module.exports: $Exports<'preact-css-transition-group/src/CSSCore'>;
}
declare module 'preact-css-transition-group/src/CSSTransitionGroup.js' {
  declare module.exports: $Exports<'preact-css-transition-group/src/CSSTransitionGroup'>;
}
declare module 'preact-css-transition-group/src/CSSTransitionGroupChild.js' {
  declare module.exports: $Exports<'preact-css-transition-group/src/CSSTransitionGroupChild'>;
}
declare module 'preact-css-transition-group/src/index.js' {
  declare module.exports: $Exports<'preact-css-transition-group/src/index'>;
}
declare module 'preact-css-transition-group/src/TransitionChildMapping.js' {
  declare module.exports: $Exports<'preact-css-transition-group/src/TransitionChildMapping'>;
}
declare module 'preact-css-transition-group/src/TransitionEvents.js' {
  declare module.exports: $Exports<'preact-css-transition-group/src/TransitionEvents'>;
}
declare module 'preact-css-transition-group/src/util.js' {
  declare module.exports: $Exports<'preact-css-transition-group/src/util'>;
}
declare module 'preact-css-transition-group/tests/index.js' {
  declare module.exports: $Exports<'preact-css-transition-group/tests/index'>;
}
declare module 'preact-css-transition-group/tests/karma.conf.js' {
  declare module.exports: $Exports<'preact-css-transition-group/tests/karma.conf'>;
}
