// flow-typed signature: 2e9c7fcc67292f56acfaade0e2fdbb2e
// flow-typed version: <<STUB>>/preact-router_v^2.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-router/dist/preact-router' {
  declare module.exports: any;
}

declare module 'preact-router/dist/preact-router.min' {
  declare module.exports: any;
}

declare module 'preact-router/src/index' {
  declare module.exports: any;
}

declare module 'preact-router/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-router/dist/preact-router.js' {
  declare module.exports: $Exports<'preact-router/dist/preact-router'>;
}
declare module 'preact-router/dist/preact-router.min.js' {
  declare module.exports: $Exports<'preact-router/dist/preact-router.min'>;
}
declare module 'preact-router/src/index.js' {
  declare module.exports: $Exports<'preact-router/src/index'>;
}
declare module 'preact-router/src/util.js' {
  declare module.exports: $Exports<'preact-router/src/util'>;
}
