// flow-typed signature: 295a381d8855d82b516738740206ccf9
// flow-typed version: <<STUB>>/proptypes_v^0.14.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'proptypes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'proptypes/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'proptypes/index' {
  declare module.exports: $Exports<'proptypes'>;
}
declare module 'proptypes/index.js' {
  declare module.exports: $Exports<'proptypes'>;
}
declare module 'proptypes/src/index.js' {
  declare module.exports: $Exports<'proptypes/src/index'>;
}
