// flow-typed signature: 661c89b2d3e3952424d9da0b70adefb4
// flow-typed version: <<STUB>>/v8-lazy-parse-webpack-plugin_v^0.3.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'v8-lazy-parse-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'v8-lazy-parse-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'v8-lazy-parse-webpack-plugin/V8LazyParsedFunctionModulePlugin' {
  declare module.exports: any;
}

declare module 'v8-lazy-parse-webpack-plugin/V8LazyParsedFunctionModuleTemplatePlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'v8-lazy-parse-webpack-plugin/index' {
  declare module.exports: $Exports<'v8-lazy-parse-webpack-plugin'>;
}
declare module 'v8-lazy-parse-webpack-plugin/index.js' {
  declare module.exports: $Exports<'v8-lazy-parse-webpack-plugin'>;
}
declare module 'v8-lazy-parse-webpack-plugin/V8LazyParsedFunctionModulePlugin.js' {
  declare module.exports: $Exports<'v8-lazy-parse-webpack-plugin/V8LazyParsedFunctionModulePlugin'>;
}
declare module 'v8-lazy-parse-webpack-plugin/V8LazyParsedFunctionModuleTemplatePlugin.js' {
  declare module.exports: $Exports<'v8-lazy-parse-webpack-plugin/V8LazyParsedFunctionModuleTemplatePlugin'>;
}
